### ISSUE TITLE
type error in prepare_data

### ISSUE THREAD

**Issue by woobin09** [huangshiyu13/RPNplus#10]
After nn starts the training, it outputs a type error in data_engine.py in prepare_data,
line: fg_inx = fg_idx[:fg_num]

TypeError: slice indices must be integers or None or have an __index__ method

I just downloaded the precarious_dataset and updated the folders on train.py

**Comment by huangshiyu13** [comment]
It seems that `fg_num` is wrong. You can have a check on it.

**Comment by woobin09** [comment]
i had it print and the number comes out to be a float
Just converted the float->int and it seems to be training now
