### ISSUE TITLE
How to use the precarious_dataset & synthetic_dataset datasets to train model?

### ISSUE THREAD

**Issue by baiyancheng20** [huangshiyu13/RPNplus#2]
@huangshiyu13 Hi, thank you for sharing the code. I have dowloaded the two datasets. I can train the model with the following data path settings:
`imageLoadDir = Dataset/precarious_dataset/train/`
 `anoLoadDir = precarious_dataset/trainAno/`.
If I also want to use the synthetic_dataset dataset, how should I set the data path?

**Comment by huangshiyu13** [comment]
I think one way to solve this problem is that you merge these two datasets by hand.
