### ISSUE TITLE
What does the 'wandhG' mean ?

### ISSUE THREAD

**Issue by liuguiyangnwpu** [huangshiyu13/RPNplus#4]
hi,
I want to use RPNPlus to detect the object?
and I want to use this model to extract the proposal area.
And I changed the Input Image size to (224 ,224 ,1). But I don't know how to change the 'wandhG'?

```
wandhG = [[100.0, 100.0], [300.0, 300.0], [500.0, 500.0],
          [200.0, 100.0], [370.0, 185.0], [440.0, 220.0],
          [100.0, 200.0], [185.0, 370.0], [220.0, 440.0]]
```

thx

**Comment by huangshiyu13** [comment]
If you change the input size, you should change the hidden layer's size.  As for the wandhG, you should can its size to any size  you want, as long as wandhG fits your ground truth well.
